name: Build and Test

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main]

env:
    NODE_VERSION: "20"

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "npm"

            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libnss3-dev libatk-bridge2.0-dev libdrm2-dev libxcomposite-dev libxdamage-dev libxrandr-dev libgbm-dev libxss-dev libasound2-dev
                  npm ci

            - name: Build TypeScript
              run: npm run build

            - name: Test build script
              run: |
                  chmod +x build.sh
                  ./build.sh deb

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: test-build-${{ github.sha }}
                  path: dist/
                  retention-days: 7
